package com.easyselenium.report;

public interface Report {

	String PASSED_STEPS_NUM = "SELENIUMREPORTPASSEDSTEPS";
	
	String FAILED_STEPS_NUM = "SELENIUMREPORTFAILEDSTEPS";
	
	String SUITE_NAME = "SELENIUM_REPORT_SUITE_NAME";
	
	String SCRIPT_NAME = "SELENIUM_REPORT_SCRIPT_NAME";
	
	String BPC_NAME = "SELENINUM_REPORT_BPC_NAME";
	
	String STEP = "SELENIUM_REPORT_STEP";
	
	String STATUS = "SELENIUM_REPORT_STEP_STATUS";
	
	String BODY = "SELENIUMREPORTBODY";
	
}
